#!/usr/bin/env bash
set -e

# RESET
gsettings reset-recursively org.gnome.desktop.wm.keybindings

# [desktop/wm/keybindings]
gsettings set org.gnome.desktop.wm.keybindings activate-window-menu @as []
gsettings set org.gnome.desktop.wm.keybindings begin-move @as []
gsettings set org.gnome.desktop.wm.keybindings close ['<Super>d']
gsettings set org.gnome.desktop.wm.keybindings cycle-group ['<Super>grave']
gsettings set org.gnome.desktop.wm.keybindings cycle-group-backward ['<Shift><Super>grave']
gsettings set org.gnome.desktop.wm.keybindings cycle-panels @as []
gsettings set org.gnome.desktop.wm.keybindings cycle-panels-backward @as []
gsettings set org.gnome.desktop.wm.keybindings cycle-windows ['<Super>k']
gsettings set org.gnome.desktop.wm.keybindings cycle-windows-backward ['<Shift><Super>k']
gsettings set org.gnome.desktop.wm.keybindings maximize ['<Super>f']
gsettings set org.gnome.desktop.wm.keybindings minimize @as []
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-down ['<Control><Super>j']
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-left ['<Control><Super>h']
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-right ['<Control><Super>l']
gsettings set org.gnome.desktop.wm.keybindings move-to-monitor-up ['<Control><Super>k']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-1 ['<Shift><Super>1']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-2 ['<Shift><Super>2']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-3 ['<Shift><Super>3']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-4 ['<Shift><Super>4']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-last @as []
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-left ['<Shift><Super>p']
gsettings set org.gnome.desktop.wm.keybindings move-to-workspace-right ['<Shift><Super>n']
gsettings set org.gnome.desktop.wm.keybindings panel-run-dialog @as []
gsettings set org.gnome.desktop.wm.keybindings switch-applications ['<Super>Tab']
gsettings set org.gnome.desktop.wm.keybindings switch-applications-backward ['<Shift><Super>Tab']
gsettings set org.gnome.desktop.wm.keybindings switch-group @as []
gsettings set org.gnome.desktop.wm.keybindings switch-group-backward @as []
gsettings set org.gnome.desktop.wm.keybindings switch-input-source @as []
gsettings set org.gnome.desktop.wm.keybindings switch-input-source-backward @as []
gsettings set org.gnome.desktop.wm.keybindings switch-panels ['<Alt>Tab']
gsettings set org.gnome.desktop.wm.keybindings switch-panels-backward ['<Shift><Alt>Tab']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-1 ['<Super>1']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-2 ['<Super>2']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-3 ['<Super>3']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-4 ['<Super>4']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-last @as []
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-left ['<Super>p']
gsettings set org.gnome.desktop.wm.keybindings switch-to-workspace-right ['<Super>n']
gsettings set org.gnome.desktop.wm.keybindings switch-windows @as []
gsettings set org.gnome.desktop.wm.keybindings switch-windows-backward @as []
gsettings set org.gnome.desktop.wm.keybindings toggle-fullscreen ['<Alt>f']
gsettings set org.gnome.desktop.wm.keybindings toggle-maximized @as []
gsettings set org.gnome.desktop.wm.keybindings unmaximize ['<Shift><Super>f']

# [shell/keybindings]
gsettings set org.gnome.shell.keybindings focus-active-notification @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-1 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-2 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-3 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-4 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-5 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-6 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-7 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-8 @as []
gsettings set org.gnome.shell.keybindings open-new-window-application-9 @as []
gsettings set org.gnome.shell.keybindings screen-brightness-cycle ['XF86MonBrightnessCycle']
gsettings set org.gnome.shell.keybindings screen-brightness-cycle-monitor ['<Shift>XF86MonBrightnessCycle']
gsettings set org.gnome.shell.keybindings screen-brightness-down ['XF86MonBrightnessDown']
gsettings set org.gnome.shell.keybindings screen-brightness-down-monitor ['<Shift>XF86MonBrightnessDown']
gsettings set org.gnome.shell.keybindings screen-brightness-up ['XF86MonBrightnessUp']
gsettings set org.gnome.shell.keybindings screen-brightness-up-monitor ['<Shift>XF86MonBrightnessUp']
gsettings set org.gnome.shell.keybindings screenshot ['<Shift>Print']
gsettings set org.gnome.shell.keybindings screenshot-window ['<Alt>Print']
gsettings set org.gnome.shell.keybindings shift-overview-down ['<Super><Alt>Down']
gsettings set org.gnome.shell.keybindings shift-overview-up ['<Super><Alt>Up']
gsettings set org.gnome.shell.keybindings show-screen-recording-ui ['<Shift><Super>r']
gsettings set org.gnome.shell.keybindings show-screenshot-ui ['Print']
gsettings set org.gnome.shell.keybindings switch-to-application-1 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-2 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-3 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-4 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-5 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-6 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-7 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-8 @as []
gsettings set org.gnome.shell.keybindings switch-to-application-9 @as []
gsettings set org.gnome.shell.keybindings toggle-application-view ['<Super>a']
gsettings set org.gnome.shell.keybindings toggle-message-tray ['<Super>v', '<Super>m']
gsettings set org.gnome.shell.keybindings toggle-overview @as []
gsettings set org.gnome.shell.keybindings toggle-quick-settings ['<Super>s']

#[mutter/keybindings]
gsettings set org.gnome.mutter.keybindings switch-monitor "['XF86Display']"
